import { Farmer, Product } from './types';

export const CATEGORIES = ['All', 'Vegetables', 'Fruits', 'Dairy', 'Honey', 'Herbs', 'Grains'];

export const FARMERS: Farmer[] = [
  { id: 'f1', name: 'Green Valley Organics', location: 'Portland, OR', rating: 4.8, verified: true, imageUrl: 'https://picsum.photos/seed/f1/200/200', joinedDate: '2021-03-15' },
  { id: 'f2', name: 'Hilltop Harvest', location: 'Salem, OR', rating: 4.6, verified: true, imageUrl: 'https://picsum.photos/seed/f2/200/200', joinedDate: '2022-01-10' },
  { id: 'f3', name: 'Sunny Side Acres', location: 'Eugene, OR', rating: 4.9, verified: true, imageUrl: 'https://picsum.photos/seed/f3/200/200', joinedDate: '2020-11-05' },
  { id: 'f4', name: 'River Bend Farm', location: 'Bend, OR', rating: 4.7, verified: false, imageUrl: 'https://picsum.photos/seed/f4/200/200', joinedDate: '2023-05-20' },
  { id: 'f5', name: 'Coastal Roots', location: 'Newport, OR', rating: 4.5, verified: true, imageUrl: 'https://picsum.photos/seed/f5/200/200', joinedDate: '2022-08-14' },
  { id: 'f6', name: 'Mountain View Dairy', location: 'Hood River, OR', rating: 4.9, verified: true, imageUrl: 'https://picsum.photos/seed/f6/200/200', joinedDate: '2019-04-01' },
  { id: 'f7', name: 'Golden Fields', location: 'Medford, OR', rating: 4.4, verified: false, imageUrl: 'https://picsum.photos/seed/f7/200/200', joinedDate: '2023-02-28' },
  { id: 'f8', name: 'Urban Greens', location: 'Portland, OR', rating: 4.8, verified: true, imageUrl: 'https://picsum.photos/seed/f8/200/200', joinedDate: '2021-09-12' },
  { id: 'f9', name: 'Happy Hens Farm', location: 'Corvallis, OR', rating: 5.0, verified: true, imageUrl: 'https://picsum.photos/seed/f9/200/200', joinedDate: '2020-06-30' },
  { id: 'f10', name: 'Orchard Hill', location: 'Ashland, OR', rating: 4.7, verified: true, imageUrl: 'https://picsum.photos/seed/f10/200/200', joinedDate: '2022-11-22' },
];

export const PRODUCTS: Product[] = [
  { id: 'p1', farmerId: 'f1', name: 'Heirloom Carrots', description: 'Crunchy, sweet, and colorful heirloom carrots harvested this morning.', category: 'Vegetables', price: 3.50, unit: 'bunch', stock: 50, isOrganic: true, harvestDate: '2023-10-25', imageUrl: 'https://picsum.photos/seed/carrots/400/400', rating: 4.8, reviewsCount: 124 },
  { id: 'p2', farmerId: 'f1', name: 'Red Kale', description: 'Fresh, nutrient-packed red kale. Perfect for salads or chips.', category: 'Vegetables', price: 2.75, unit: 'bunch', stock: 30, isOrganic: true, harvestDate: '2023-10-26', imageUrl: 'https://picsum.photos/seed/kale/400/400', rating: 4.5, reviewsCount: 45 },
  { id: 'p3', farmerId: 'f2', name: 'Roma Tomatoes', description: 'Vine-ripened Roma tomatoes, bursting with flavor.', category: 'Vegetables', price: 4.00, unit: 'kg', stock: 100, isOrganic: true, harvestDate: '2023-10-24', imageUrl: 'https://picsum.photos/seed/tomatoes/400/400', rating: 4.7, reviewsCount: 89 },
  { id: 'p4', farmerId: 'f2', name: 'Sweet Corn', description: 'Golden sweet corn, picked at the peak of sweetness.', category: 'Vegetables', price: 1.00, unit: 'ear', stock: 200, isOrganic: false, harvestDate: '2023-10-25', imageUrl: 'https://picsum.photos/seed/corn/400/400', rating: 4.6, reviewsCount: 32 },
  { id: 'p5', farmerId: 'f3', name: 'Fuji Apples', description: 'Crisp and sweet Fuji apples from the orchard.', category: 'Fruits', price: 5.50, unit: 'kg', stock: 150, isOrganic: true, harvestDate: '2023-10-20', imageUrl: 'https://picsum.photos/seed/apples/400/400', rating: 4.9, reviewsCount: 210 },
  { id: 'p6', farmerId: 'f3', name: 'Bartlett Pears', description: 'Juicy Bartlett pears, great for snacking or baking.', category: 'Fruits', price: 4.80, unit: 'kg', stock: 80, isOrganic: true, harvestDate: '2023-10-22', imageUrl: 'https://picsum.photos/seed/pears/400/400', rating: 4.8, reviewsCount: 56 },
  { id: 'p7', farmerId: 'f6', name: 'Raw Milk Cheese', description: 'Aged artisanal raw milk cheese with a sharp flavor.', category: 'Dairy', price: 12.00, unit: 'block', stock: 20, isOrganic: true, harvestDate: '2023-09-15', imageUrl: 'https://picsum.photos/seed/cheese/400/400', rating: 4.9, reviewsCount: 312 },
  { id: 'p8', farmerId: 'f6', name: 'Fresh Cream', description: 'Rich, thick cream from grass-fed cows.', category: 'Dairy', price: 6.00, unit: 'bottle', stock: 15, isOrganic: true, harvestDate: '2023-10-26', imageUrl: 'https://picsum.photos/seed/cream/400/400', rating: 5.0, reviewsCount: 88 },
  { id: 'p9', farmerId: 'f9', name: 'Free Range Eggs', description: 'Large brown eggs from happy, pasture-raised hens.', category: 'Dairy', price: 7.00, unit: 'dozen', stock: 40, isOrganic: true, harvestDate: '2023-10-27', imageUrl: 'https://picsum.photos/seed/eggs/400/400', rating: 4.8, reviewsCount: 450 },
  { id: 'p10', farmerId: 'f5', name: 'Wildflower Honey', description: 'Raw, unfiltered honey with floral notes.', category: 'Honey', price: 15.00, unit: 'jar', stock: 25, isOrganic: true, harvestDate: '2023-08-10', imageUrl: 'https://picsum.photos/seed/honey/400/400', rating: 5.0, reviewsCount: 120 },
  { id: 'p11', farmerId: 'f8', name: 'Fresh Basil', description: 'Aromatic basil bunch, essential for pesto.', category: 'Herbs', price: 3.00, unit: 'bunch', stock: 20, isOrganic: true, harvestDate: '2023-10-27', imageUrl: 'https://picsum.photos/seed/basil/400/400', rating: 4.7, reviewsCount: 30 },
  { id: 'p12', farmerId: 'f8', name: 'Rosemary', description: 'Woody rosemary sprigs.', category: 'Herbs', price: 2.50, unit: 'bunch', stock: 15, isOrganic: true, harvestDate: '2023-10-25', imageUrl: 'https://picsum.photos/seed/rosemary/400/400', rating: 4.6, reviewsCount: 15 },
  { id: 'p13', farmerId: 'f7', name: 'Rolled Oats', description: 'Classic rolled oats, perfect for breakfast.', category: 'Grains', price: 4.00, unit: 'bag', stock: 60, isOrganic: false, harvestDate: '2023-09-01', imageUrl: 'https://picsum.photos/seed/oats/400/400', rating: 4.5, reviewsCount: 67 },
  { id: 'p14', farmerId: 'f7', name: 'Whole Wheat Flour', description: 'Stone-ground whole wheat flour.', category: 'Grains', price: 5.00, unit: 'bag', stock: 45, isOrganic: false, harvestDate: '2023-09-10', imageUrl: 'https://picsum.photos/seed/flour/400/400', rating: 4.4, reviewsCount: 22 },
  { id: 'p15', farmerId: 'f4', name: 'Potatoes (Russet)', description: 'Versatile Russet potatoes, great for baking.', category: 'Vegetables', price: 3.00, unit: 'kg', stock: 300, isOrganic: false, harvestDate: '2023-10-15', imageUrl: 'https://picsum.photos/seed/potatoes/400/400', rating: 4.3, reviewsCount: 90 },
  { id: 'p16', farmerId: 'f10', name: 'Blueberries', description: 'Plump and sweet late-season blueberries.', category: 'Fruits', price: 6.00, unit: 'pint', stock: 40, isOrganic: true, harvestDate: '2023-10-24', imageUrl: 'https://picsum.photos/seed/blueberries/400/400', rating: 4.9, reviewsCount: 110 },
  { id: 'p17', farmerId: 'f10', name: 'Peaches', description: 'Juicy peaches with a soft fuzz.', category: 'Fruits', price: 5.00, unit: 'kg', stock: 25, isOrganic: true, harvestDate: '2023-10-23', imageUrl: 'https://picsum.photos/seed/peaches/400/400', rating: 4.8, reviewsCount: 75 },
  { id: 'p18', farmerId: 'f1', name: 'Beets', description: 'Earthy red beets, greens attached.', category: 'Vegetables', price: 3.25, unit: 'bunch', stock: 35, isOrganic: true, harvestDate: '2023-10-26', imageUrl: 'https://picsum.photos/seed/beets/400/400', rating: 4.6, reviewsCount: 28 },
  { id: 'p19', farmerId: 'f2', name: 'Cucumber', description: 'Crunchy slicing cucumbers.', category: 'Vegetables', price: 1.50, unit: 'each', stock: 60, isOrganic: true, harvestDate: '2023-10-27', imageUrl: 'https://picsum.photos/seed/cucumber/400/400', rating: 4.5, reviewsCount: 54 },
  { id: 'p20', farmerId: 'f5', name: 'Honeycomb', description: 'Pure honeycomb straight from the hive.', category: 'Honey', price: 20.00, unit: 'box', stock: 10, isOrganic: true, harvestDate: '2023-08-15', imageUrl: 'https://picsum.photos/seed/honeycomb/400/400', rating: 5.0, reviewsCount: 40 },
];
